# Generated by Django 5.0.7 on 2024-07-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
